name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          path: main
      - name: Build all
        run: |
          cd $GITHUB_WORKSPACE/main
          bazel build //...
      - name: Run tests
        run: |
          cd $GITHUB_WORKSPACE/main
          bazel test --keep_going --test_strategy=exclusive --build_event_json_file=$GITHUB_WORKSPACE/build-events.jsonl //...
      - name: Upload test reports
        run: |
          cd $GITHUB_WORKSPACE/main
          bazel run @rules_contest//contest:render_test_results -- $GITHUB_WORKSPACE/build-events.jsonl > $GITHUB_WORKSPACE/report.md
          git config --global user.name "Automated Testing"
          git config --global user.email "testing@example.com"
          cd $GITHUB_WORKSPACE
          mkdir report
          cd report
          git init
          git remote add origin "https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}"
          git fetch --depth=1 origin report && git checkout -t origin/report || git checkout -b report
          cp $GITHUB_WORKSPACE/report.md README.md
          git add README.md
          git commit -a --allow-empty -m "Test results for commit ${{ github.sha }}"
          git push origin report
